Barberia/Barberia/urls.py
from Barberia import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from core.views import indexTemplateView
from core.registro.views import registroView
from core.login.views import inicioSesionUsuario,LogoutView
from core.agenda.views import AgendaListiView,AgendaCreateView,actualizarAgenda,eliminarAgenda

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',indexTemplateView.as_view(),name=''),
    path('iniSesion/',inicioSesionUsuario.as_view(),name='iniSesion'),
    path('regisUsua/',registroView.as_view(),name='regisUsua'),
    path('logout/',LogoutView.as_view(next_page=''),name='logout'),

    path('listaagenda',AgendaListiView.as_view(),name='listaagenda'),
    path('crearagenda/',AgendaCreateView.as_view(),name='crearagenda'),
    path('actualizaragenda/<int:pk>', actualizarAgenda.as_view(),name='actualizaragenda'),
    path('eliminaragenda/<int:pk>', eliminarAgenda.as_view(),name='eliminaragenda'),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Barberia/core/agenda/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from core.models import Barberia, Barbero
from Barberia.funciones import Opciones
from django.utils import timezone
from datetime import timedelta, datetime
from django.utils.timezone import now

opciones = Opciones()
PLANES = opciones.planes()  # Llamada al método de instancia
horarioAtencion = opciones.horario_atencion()

class Agenda(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(blank=False, null=True,default=timezone.now().date())
    plan = models.CharField(max_length=1, choices=PLANES, default=PLANES[0][0], blank=True, null=True)
    barbero = models.ForeignKey(Barbero,on_delete=models.CASCADE, default=id(1))
    horarioAtencion = models.CharField(max_length=1, choices=horarioAtencion, default=horarioAtencion[0][0], blank=True, null=True)

    def clean(self):
        # Verificar si ya existe una agenda para el mismo barbero, día y hora
        if Agenda.objects.exclude(id=self.id).filter(
                fecha__date=self.fecha.date(),
                horarioAtencion=self.horarioAtencion,
                barbero=self.barbero
        ).exists():
            raise ValidationError("El barbero ya tiene una agenda para esta hora en este día.")
        # if Agenda.objects.filter(fecha__date=self.fecha.date(), horarioAtencion=self.horarioAtencion).exists():
        #     raise ValidationError("Ya existe una agenda para esta hora en este día.")
        #
        # if Agenda.objects.filter(fecha__date=self.fecha.date(), horarioAtencion=self.horarioAtencion).exists():
        #     raise ValidationError("Ya existe una agenda para esta hora en este día.")


    def __str__(self):
        return str(self.barbero)

Barberia/core/agenda/forms.py
from django import forms
from .models import Agenda

class AgendaForm(forms.ModelForm):
    class Meta:
        model = Agenda
        fields = ['fecha','plan','barbero','horarioAtencion']

        widgets = {
            'plan':    forms.Select(attrs={ 'required': True}),
            'barbero': forms.Select(attrs={ 'required': True}),
            'fecha': forms.SelectDateWidget(attrs={'type':'date','readonly':True}),
            'horarioAtencion': forms.Select(attrs={ 'required': True}),
}

Barberia/core/agenda/views.py
import json

from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView,ListView,CreateView,UpdateView, DeleteView

from .forms import AgendaForm
from .models import Agenda

class AgendaListiView(ListView):
    template_name ="Agenda/listaAgendas.html"
    context_object_name = "Agenda"
    model = Agenda
    #queryset = Agenda.objects.filter(usuario=id())

    def get_queryset(self):
        # Filtrar las agendas solo para el usuario autenticado
        return Agenda.objects.filter(usuario=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Listado de Agenda"
        context['query'] = self.request.GET.get("query")
        return context

class AgendaCreateView(CreateView):
    template_name = 'Agenda/agendar_citas.html'
    model = Agenda
    form_class = AgendaForm
    success_url = reverse_lazy('listaagenda')

    def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['tituloform'] = "Formulario De Agenda"
      context['titulo'] = "Agenda"
      context['boton'] = "Agregar Agenda"
      context['listar_url'] = '/listaagenda/'
      context['action_save'] = '/crearagenda/'
      return context

    def form_valid(self, form):
        form.instance.usuario = self.request.user  # Asigna el usuario actual
        return super().form_valid(form)

    # def form_invalid(self, form):
    #     # En caso de errores de validación, devolvemos un JSON con los errores
    #     errors = form.errors.as_json()
    #     print(errors)
    #     return JsonResponse({'errors': json.loads(errors)})


class actualizarAgenda(UpdateView):
  model = Agenda
  template_name = "Agenda/agendar_citas.html"
  success_url = reverse_lazy('listaagenda')
  form_class = AgendaForm

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['action_save'] = self.request.path
    context['title'] = 'Actualización'
    context['tituloform'] = 'ACTUALIZAR AGENDA'
    context['listar_url'] = '/listaagenda/'
    context['boton'] = "Actualizar"
    return context

class eliminarAgenda(DeleteView):
  model = Agenda
  template_name = "Agenda/eliminarAgenda.html"
  success_url = reverse_lazy('listaagenda')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['action_save'] = self.request.path
    context['title'] = 'Eliminar'
    context['listar_url'] = '/listaagenda'
    context['table_title'] = 'Seguro Que Deseas Eliminar este Registro?'
    return context

  def post(self, request, pk, *args, **kwargs):
      # object = Refrigeradora.objects.get(id=pk)
      # object.estado = True
      # object.save()
      return redirect('listaagenda')

Barberia/templates/Agenda/agendar_citas.html
{% extends 'formulario.html' %}

{% load static %}

{% block formulario %}

    <!-- Selección de fecha -->
    <div class="field">
        <label class="label" for="plan">Selecciona tu plan</label>
        <div class="control">
          <div class="select is-fullwidth">
           {{ form.plan }}
          </div>
        </div>
      </div>

    <div class="field">
        <label class="label" for="fecha">Selecciona La Fecha</label>
        <div class="control date" >
          <div class="calendar" >
           {{ form.fecha }}
          </div>
        </div>
      </div>

      <!-- Selección de hora -->
       <div class="field">
        <label class="label" for="horarioAtencion">Selecciona la Hora</label>
        <div class="control">
          <div class="select is-fullwidth">
           {{ form.horarioAtencion }}
          </div>
        </div>
      </div>

      <!-- Selección de barbero -->
      <div class="field">
        <label class="label" for="barbero">Selecciona tu barbero</label>
        <div class="control">
          <div class="select is-fullwidth">
           {{ form.barbero }}
          </div>
        </div>
      </div>

{% endblock %}

Barberia/templates/Agenda/eliminarAgenda.html
{% extends "baseEliminar.html" %}
{% block header %}
    {% include "navbar.html" %}
{% endblock %}
{% load static %}

{% block eliminarbase %}


          <div class="table-container">
            <table class="table is-fullwidth is-striped">
                <thead>
                    <tr>
                        <th>Barbero</th>
                        <th>Fecha</th>
                        <th>Servicio</th>
                        <th>Horario de Atención</th> <!-- Este campo puede ser opcional. -->
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ object.barbero }}</td>
                        <td>{{ object.fecha | date:"d/m/Y " }}</td>
                        <td>{{ object.get_plan_display }}</td>
                        <td>{{ object.get_horarioAtencion_display }}</td> 
                    </tr>
                </tbody>
            </table>
      </div>
{% endblock %}

Barberia/templates/Agenda/listaAgendas.html
{% extends 'index.html' %}
{% block header %}
    {% include 'navbar.html' %}
{% endblock %}
{% load static %}
{% block secciones %}
    <h1 class="title has-text-centered">Tus Citas Agendadas</h1>

    <div class="table-container">
        <table class="table is-fullwidth is-striped">
            <thead>
                <tr>
                    <th>Barbero</th>
                    <th>Fecha</th>
                    <th>Servicio</th>
                    <th>Horario de Atención</th> <!-- Este campo puede ser opcional. -->
                    <th>Horario de Atención</th> <!-- Este campo puede ser opcional. -->
                </tr>
            </thead>
            <tbody>
                {% for object in Agenda %}
                    <tr>
                        <td>{{ object.barbero }}</td>
                        <td>{{ object.fecha | date:"d/m/Y " }}</td>
                        <td>{{ object.get_plan_display }}</td>

                        <td>{{ object.get_horarioAtencion_display }}</td> <!-- Aquí puedes agregar lógica si manejas diferentes estados de la cita -->
                        <td>
                            <a href="{% url  'actualizaragenda' object.id %}"><button class="button is-warning">Editar</button></a>
                            <a href="{% url  'eliminaragenda' object.id %}"> <button class="button is-danger">Eliminar</button></a>
                        </td>
                {% empty %}
                    <tr>
                        <td colspan="4" class="has-text-centered">No tienes citas agendadas.</td>
                    </tr>

                {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}